# Generated by Django 3.1.2 on 2020-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
